package com.example.uniclub.enums;

public enum WalletTransactionTypeEnum {

    ADD,
    REDUCE,
    TRANSFER,
    UNI_TO_CLUB,
    CLUB_TO_MEMBER,
    EVENT_BUDGET_GRANT,
    EVENT_REFUND_REMAINING,
    COMMIT_LOCK,
    REFUND_COMMIT,
    BONUS_REWARD,
    RETURN_SURPLUS,
    REDEEM_PRODUCT,
    REFUND_PRODUCT,
    EVENT_REDEEM_PRODUCT,
    EVENT_REFUND_PRODUCT,
    CLUB_RECEIVE_REDEEM,
    CLUB_REFUND,
    ADMIN_ADJUST,
    MEMBER_PENALTY,
    CLUB_FROM_PENALTY,
    EVENT_BUDGET_FORFEIT,
    MEMBER_REWARD,
    CLUB_REWARD_DISTRIBUTE,
    PRODUCT_CREATION_COST,

}
